-- 코드를 입력하세요
WITH answer AS (
    SELECT BOOK_ID, SUM(SALES) AS SUM
    FROM BOOK_SALES 
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
    GROUP BY BOOK_ID
)
# A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, S.SUM * B.PRICE AS TOTAL_SALES
    
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SUM * B.PRICE) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN (SELECT * FROM answer) S ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY 1, 3
ORDER BY 1, 3 DESC;


# SELECT * FROM BOOK_SALES where DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'