-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * OS.TOTAL_SALES_AMOUNT AS SALES
FROM PRODUCT P
JOIN 
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
    FROM OFFLINE_SALE 
    GROUP BY PRODUCT_ID) OS ON OS.PRODUCT_ID = P.PRODUCT_ID
ORDER BY 2 DESC, 1;
    