-- 코드를 입력하세요
WITH answer AS (
    SELECT AI.ANIMAL_ID, DATEDIFF(AO.DATETIME,AI.DATETIME)
    FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO ON AO.ANIMAL_ID = AI.ANIMAL_ID
    ORDER BY 2 DESC
    LIMIT 2
    )

SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID FROM answer);