-- 코드를 입력하세요
WITH EXAM AS (
    SELECT A.CAR_ID ,A.CAR_TYPE ,ROUND((A.DAILY_FEE - (A.DAILY_FEE /100 * C.DISCOUNT_RATE)) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR  A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID 
        AND B.START_DATE <= '20221130' 
        AND B.END_DATE >='20221101'
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  C ON A.CAR_TYPE = C.CAR_TYPE 
        AND DURATION_TYPE = '30일 이상'
    WHERE A.CAR_TYPE IN('SUV','세단')
    AND B.CAR_ID IS NULL
)

SELECT * 
FROM EXAM
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;