-- 코드를 작성해주세요
WITH EXAM AS (
SELECT ID,
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
FROM ECOLI_DATA)

SELECT ID,
    CASE WHEN PER = 1 THEN 'CRITICAL'
    WHEN PER = 2 THEN 'HIGH'
    WHEN PER = 3 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM EXAM
ORDER BY 1;