-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%' AND
    AO.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY AO.ANIMAL_ID;