-- 코드를 입력하세요
-- REST_INFO에서 서울에 위치한 식당ID
-- Rest_REVIEW에서 식당 ID로 찾는데 GroupBy REST_ID, avgScore
SELECT RR.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI
JOIN REST_REVIEW RR ON RR.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RR.REST_ID
ORDER BY 6 DESC, 4 DESC;