-- 코드를 작성해주세요
# WITH EXAM AS (
#     SELECT COUNT(ID) AS FISH_COUNT, FISH_TYPE
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# )

SELECT COUNT(FI.ID) AS FISH_COUNT, FNI.FISH_NAME
FROM FISH_NAME_INFO FNI
JOIN FISH_INFO FI ON FI.FISH_TYPE = FNI.FISH_TYPE
GROUP BY 2
ORDER BY 1 DESC;