-- 코드를 작성해주세요
WITH EXAM AS (
    SELECT CASE WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 12 THEN '4Q' END QUARTER
    FROM ECOLI_DATA 
)

SELECT QUARTER, COUNT(*) AS ECOLI_COUNT
FROM EXAM
GROUP BY 1
ORDER BY 1;