SELECT
APNT_NO,    PT_NAME,    P.PT_NO,    D.MCDP_CD,  DR_NAME,    APNT_YMD
FROM
PATIENT P,
DOCTOR D,
APPOINTMENT A
WHERE
P.PT_NO = A.PT_NO
AND
A.MDDR_ID = D.DR_ID
AND
A.APNT_NO IN 
(SELECT 
APNT_NO
FROM 
APPOINTMENT 
WHERE
DATE_FORMAT(APNT_YMD,'%Y-%m-%d') = '2022-04-13'
and
APNT_CNCL_YN = 'N'
AND
MCDP_CD ='CS'
)
ORDER BY A.APNT_YMD;

# APNT_NO	PT_NAME	PT_NO	MCDP_CD	DR_NAME	APNT_YMD
# 43	바라	PT22000019	CS	니모	2022-04-13 15:30:00


# SELECT 
# *
# FROM 
# APPOINTMENT 
# WHERE
# DATE_FORMAT(APNT_YMD,'%Y-%m-%d') = '2022-04-13'
# and
# APNT_CNCL_YN = 'N'
# AND
# MCDP_CD ='CS';