-- 코드를 작성해주세요
SELECT HG.EMP_NO, HE.EMP_NAME, HG.GRADE,
    CASE WHEN HG.GRADE = 'S' THEN HE.SAL * 0.2
        WHEN HG.GRADE = 'A' THEN HE.SAL * 0.15
        WHEN HG.GRADE = 'B' THEN HE.SAL * 0.1
        ELSE HE.SAL * 0 END AS BONUS
FROM HR_EMPLOYEES HE
JOIN (SELECT EMP_NO, 
        CASE WHEN AVG(SCORE) >= 96 THEN 'S' 
            WHEN AVG(SCORE) >= 90 THEN 'A'
            WHEN AVG(SCORE) >= 80 THEN 'B'
            ELSE 'C' END AS GRADE
    FROM HR_GRADE
    GROUP BY 1) HG ON HG.EMP_NO = HE.EMP_NO
ORDER BY 1;