-- 코드를 입력하세요
WITH a AS (
    SELECT MEMBER_ID, COUNT(*)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 2 DESC
    LIMIT 1
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE MP.MEMBER_ID = (SELECT MEMBER_ID FROM a)
ORDER BY 3, 2;