-- 코드를 입력하세요
WITH EXAM AS (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE >= '2022-08-01' and START_DATE <= '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5
)

SELECT MONTH(START_DATE) AS MONTH,
    CAR_ID, 
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM EXAM)
    AND START_DATE >= '2022-08-01' and START_DATE <= '2022-10-31'
GROUP BY 1,2
ORDER BY 1, 2 DESC;