-- 코드를 입력하세요
WITH EXAM AS(
    SELECT
        DISTINCT CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        DATE_FORMAT(START_DATE,'%Y-%m-%d') >= '2022-10-01'
)

SELECT 
    CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR
WHERE
    CAR_ID IN (SELECT CAR_ID FROM EXAM) AND
    CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;