-- 코드를 작성해주세요
WITH EXAM AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO FI 
    GROUP BY FISH_TYPE
)

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI 
JOIN FISH_NAME_INFO FNI ON FNI.FISH_TYPE = FI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (SELECT FISH_TYPE, LENGTH FROM EXAM)
ORDER BY 1;