-- 코드를 작성해주세요
WITH EXAM AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
    ORDER BY 2 DESC
LIMIT 1)


SELECT E.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN EXAM E ON E.EMP_NO = HE.EMP_NO
WHERE HE.EMP_NO = (SELECT EMP_NO FROM EXAM);
