-- 코드를 입력하세요
SELECT A.CATEGORY, MAX(PRICE) AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT 
        GROUP BY CATEGORY) B
        ON A.CATEGORY = B.CATEGORY
        AND A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY 1
ORDER BY 2 DESC;