-- 코드를 작성해주세요
WITH EXAM AS (
SELECT ID,
    FISH_TYPE, 
    LENGTH,
    CASE WHEN LENGTH <= 10 THEN 10
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH END AS LEN
FROM FISH_INFO
)
    
SELECT COUNT(ID) AS FISH_COUNT, 
    MAX(LENGTH) AS MAX_LENGTH, 
    FISH_TYPE 
FROM EXAM
GROUP BY FISH_TYPE 
HAVING AVG(LEN) >= 33
ORDER BY FISH_TYPE;